/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.ipam.demo.avro;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class Router extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -3041847465540703048L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Router\",\"namespace\":\"com.ipam.demo.avro\",\"fields\":[{\"name\":\"id\",\"type\":[\"null\",\"long\"],\"default\":null},{\"name\":\"title\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"serial\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"ports\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"record\",\"name\":\"Port\",\"fields\":[{\"name\":\"id\",\"type\":[\"null\",\"long\"],\"default\":null},{\"name\":\"name\",\"type\":[\"null\",\"string\"],\"default\":null}]}},\"default\":[]}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<Router> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<Router> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<Router> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<Router> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<Router> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this Router to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a Router from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a Router instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static Router fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.Long id;
  private java.lang.CharSequence title;
  private java.lang.CharSequence serial;
  private java.util.List<com.ipam.demo.avro.Port> ports;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Router() {}

  /**
   * All-args constructor.
   * @param id The new value for id
   * @param title The new value for title
   * @param serial The new value for serial
   * @param ports The new value for ports
   */
  public Router(java.lang.Long id, java.lang.CharSequence title, java.lang.CharSequence serial, java.util.List<com.ipam.demo.avro.Port> ports) {
    this.id = id;
    this.title = title;
    this.serial = serial;
    this.ports = ports;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return id;
    case 1: return title;
    case 2: return serial;
    case 3: return ports;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: id = (java.lang.Long)value$; break;
    case 1: title = (java.lang.CharSequence)value$; break;
    case 2: serial = (java.lang.CharSequence)value$; break;
    case 3: ports = (java.util.List<com.ipam.demo.avro.Port>)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'id' field.
   * @return The value of the 'id' field.
   */
  public java.lang.Long getId() {
    return id;
  }


  /**
   * Sets the value of the 'id' field.
   * @param value the value to set.
   */
  public void setId(java.lang.Long value) {
    this.id = value;
  }

  /**
   * Gets the value of the 'title' field.
   * @return The value of the 'title' field.
   */
  public java.lang.CharSequence getTitle() {
    return title;
  }


  /**
   * Sets the value of the 'title' field.
   * @param value the value to set.
   */
  public void setTitle(java.lang.CharSequence value) {
    this.title = value;
  }

  /**
   * Gets the value of the 'serial' field.
   * @return The value of the 'serial' field.
   */
  public java.lang.CharSequence getSerial() {
    return serial;
  }


  /**
   * Sets the value of the 'serial' field.
   * @param value the value to set.
   */
  public void setSerial(java.lang.CharSequence value) {
    this.serial = value;
  }

  /**
   * Gets the value of the 'ports' field.
   * @return The value of the 'ports' field.
   */
  public java.util.List<com.ipam.demo.avro.Port> getPorts() {
    return ports;
  }


  /**
   * Sets the value of the 'ports' field.
   * @param value the value to set.
   */
  public void setPorts(java.util.List<com.ipam.demo.avro.Port> value) {
    this.ports = value;
  }

  /**
   * Creates a new Router RecordBuilder.
   * @return A new Router RecordBuilder
   */
  public static com.ipam.demo.avro.Router.Builder newBuilder() {
    return new com.ipam.demo.avro.Router.Builder();
  }

  /**
   * Creates a new Router RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Router RecordBuilder
   */
  public static com.ipam.demo.avro.Router.Builder newBuilder(com.ipam.demo.avro.Router.Builder other) {
    if (other == null) {
      return new com.ipam.demo.avro.Router.Builder();
    } else {
      return new com.ipam.demo.avro.Router.Builder(other);
    }
  }

  /**
   * Creates a new Router RecordBuilder by copying an existing Router instance.
   * @param other The existing instance to copy.
   * @return A new Router RecordBuilder
   */
  public static com.ipam.demo.avro.Router.Builder newBuilder(com.ipam.demo.avro.Router other) {
    if (other == null) {
      return new com.ipam.demo.avro.Router.Builder();
    } else {
      return new com.ipam.demo.avro.Router.Builder(other);
    }
  }

  /**
   * RecordBuilder for Router instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Router>
    implements org.apache.avro.data.RecordBuilder<Router> {

    private java.lang.Long id;
    private java.lang.CharSequence title;
    private java.lang.CharSequence serial;
    private java.util.List<com.ipam.demo.avro.Port> ports;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.ipam.demo.avro.Router.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.title)) {
        this.title = data().deepCopy(fields()[1].schema(), other.title);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.serial)) {
        this.serial = data().deepCopy(fields()[2].schema(), other.serial);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.ports)) {
        this.ports = data().deepCopy(fields()[3].schema(), other.ports);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
    }

    /**
     * Creates a Builder by copying an existing Router instance
     * @param other The existing instance to copy.
     */
    private Builder(com.ipam.demo.avro.Router other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.title)) {
        this.title = data().deepCopy(fields()[1].schema(), other.title);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.serial)) {
        this.serial = data().deepCopy(fields()[2].schema(), other.serial);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.ports)) {
        this.ports = data().deepCopy(fields()[3].schema(), other.ports);
        fieldSetFlags()[3] = true;
      }
    }

    /**
      * Gets the value of the 'id' field.
      * @return The value.
      */
    public java.lang.Long getId() {
      return id;
    }


    /**
      * Sets the value of the 'id' field.
      * @param value The value of 'id'.
      * @return This builder.
      */
    public com.ipam.demo.avro.Router.Builder setId(java.lang.Long value) {
      validate(fields()[0], value);
      this.id = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'id' field has been set.
      * @return True if the 'id' field has been set, false otherwise.
      */
    public boolean hasId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'id' field.
      * @return This builder.
      */
    public com.ipam.demo.avro.Router.Builder clearId() {
      id = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'title' field.
      * @return The value.
      */
    public java.lang.CharSequence getTitle() {
      return title;
    }


    /**
      * Sets the value of the 'title' field.
      * @param value The value of 'title'.
      * @return This builder.
      */
    public com.ipam.demo.avro.Router.Builder setTitle(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.title = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'title' field has been set.
      * @return True if the 'title' field has been set, false otherwise.
      */
    public boolean hasTitle() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'title' field.
      * @return This builder.
      */
    public com.ipam.demo.avro.Router.Builder clearTitle() {
      title = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'serial' field.
      * @return The value.
      */
    public java.lang.CharSequence getSerial() {
      return serial;
    }


    /**
      * Sets the value of the 'serial' field.
      * @param value The value of 'serial'.
      * @return This builder.
      */
    public com.ipam.demo.avro.Router.Builder setSerial(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.serial = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'serial' field has been set.
      * @return True if the 'serial' field has been set, false otherwise.
      */
    public boolean hasSerial() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'serial' field.
      * @return This builder.
      */
    public com.ipam.demo.avro.Router.Builder clearSerial() {
      serial = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'ports' field.
      * @return The value.
      */
    public java.util.List<com.ipam.demo.avro.Port> getPorts() {
      return ports;
    }


    /**
      * Sets the value of the 'ports' field.
      * @param value The value of 'ports'.
      * @return This builder.
      */
    public com.ipam.demo.avro.Router.Builder setPorts(java.util.List<com.ipam.demo.avro.Port> value) {
      validate(fields()[3], value);
      this.ports = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'ports' field has been set.
      * @return True if the 'ports' field has been set, false otherwise.
      */
    public boolean hasPorts() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'ports' field.
      * @return This builder.
      */
    public com.ipam.demo.avro.Router.Builder clearPorts() {
      ports = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Router build() {
      try {
        Router record = new Router();
        record.id = fieldSetFlags()[0] ? this.id : (java.lang.Long) defaultValue(fields()[0]);
        record.title = fieldSetFlags()[1] ? this.title : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.serial = fieldSetFlags()[2] ? this.serial : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.ports = fieldSetFlags()[3] ? this.ports : (java.util.List<com.ipam.demo.avro.Port>) defaultValue(fields()[3]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<Router>
    WRITER$ = (org.apache.avro.io.DatumWriter<Router>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<Router>
    READER$ = (org.apache.avro.io.DatumReader<Router>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    if (this.id == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeLong(this.id);
    }

    if (this.title == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.title);
    }

    if (this.serial == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.serial);
    }

    long size0 = this.ports.size();
    out.writeArrayStart();
    out.setItemCount(size0);
    long actualSize0 = 0;
    for (com.ipam.demo.avro.Port e0: this.ports) {
      actualSize0++;
      out.startItem();
      e0.customEncode(out);
    }
    out.writeArrayEnd();
    if (actualSize0 != size0)
      throw new java.util.ConcurrentModificationException("Array-size written was " + size0 + ", but element count was " + actualSize0 + ".");

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      if (in.readIndex() != 1) {
        in.readNull();
        this.id = null;
      } else {
        this.id = in.readLong();
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.title = null;
      } else {
        this.title = in.readString(this.title instanceof Utf8 ? (Utf8)this.title : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.serial = null;
      } else {
        this.serial = in.readString(this.serial instanceof Utf8 ? (Utf8)this.serial : null);
      }

      long size0 = in.readArrayStart();
      java.util.List<com.ipam.demo.avro.Port> a0 = this.ports;
      if (a0 == null) {
        a0 = new SpecificData.Array<com.ipam.demo.avro.Port>((int)size0, SCHEMA$.getField("ports").schema());
        this.ports = a0;
      } else a0.clear();
      SpecificData.Array<com.ipam.demo.avro.Port> ga0 = (a0 instanceof SpecificData.Array ? (SpecificData.Array<com.ipam.demo.avro.Port>)a0 : null);
      for ( ; 0 < size0; size0 = in.arrayNext()) {
        for ( ; size0 != 0; size0--) {
          com.ipam.demo.avro.Port e0 = (ga0 != null ? ga0.peek() : null);
          if (e0 == null) {
            e0 = new com.ipam.demo.avro.Port();
          }
          e0.customDecode(in);
          a0.add(e0);
        }
      }

    } else {
      for (int i = 0; i < 4; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          if (in.readIndex() != 1) {
            in.readNull();
            this.id = null;
          } else {
            this.id = in.readLong();
          }
          break;

        case 1:
          if (in.readIndex() != 1) {
            in.readNull();
            this.title = null;
          } else {
            this.title = in.readString(this.title instanceof Utf8 ? (Utf8)this.title : null);
          }
          break;

        case 2:
          if (in.readIndex() != 1) {
            in.readNull();
            this.serial = null;
          } else {
            this.serial = in.readString(this.serial instanceof Utf8 ? (Utf8)this.serial : null);
          }
          break;

        case 3:
          long size0 = in.readArrayStart();
          java.util.List<com.ipam.demo.avro.Port> a0 = this.ports;
          if (a0 == null) {
            a0 = new SpecificData.Array<com.ipam.demo.avro.Port>((int)size0, SCHEMA$.getField("ports").schema());
            this.ports = a0;
          } else a0.clear();
          SpecificData.Array<com.ipam.demo.avro.Port> ga0 = (a0 instanceof SpecificData.Array ? (SpecificData.Array<com.ipam.demo.avro.Port>)a0 : null);
          for ( ; 0 < size0; size0 = in.arrayNext()) {
            for ( ; size0 != 0; size0--) {
              com.ipam.demo.avro.Port e0 = (ga0 != null ? ga0.peek() : null);
              if (e0 == null) {
                e0 = new com.ipam.demo.avro.Port();
              }
              e0.customDecode(in);
              a0.add(e0);
            }
          }
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










