services:
  postgres:
    image: postgres:17
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: testdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: testdb

  # app:
  #   build: .
  #   ports:
  #     - "8081:8081"
  #   depends_on:
  #     - postgres
