apiVersion: v1
kind: Secret
metadata:
  name: ipam-db-secret
type: Opaque
stringData:
  DB_URL: {{ .Values.db.url | quote }}
  DB_USERNAME: {{ .Values.db.username | quote }}
  DB_PASSWORD: {{ .Values.db.password | quote }}
